#!/bin/bash
# /etc/update-motd.d/01-server-intro
printf "This is a shared server on the UCD network, provided to you free of charge by"
echo "$(tput -T xterm setaf 2)"
printf "
db    db  .o88b. d8888b. d8b   db d88888b d888888b .d8888.  .d88b.   .o88b. 
88    88 d8P  Y8 88  \`8D 888o  88 88'     \`~~88~~' 88'  YP .8P  Y8. d8P  Y8 
88    88 8P      88   88 88V8o 88 88ooooo    88    \`8bo.   88    88 8P      
88    88 8b      88   88 88 V8o88 88~~~~~    88      \`Y8b. 88    88 8b      
88b  d88 Y8b  d8 88  .8D 88  V888 88.        88    db   8D \`8b  d8' Y8b  d8
~Y8888P'  \`Y88P' Y8888D' VP   V8P Y88888P    YP    \`8888Y'  \`Y88P'   \`Y88P'"

echo "$(tput -T xterm sgr0)"
printf "
On a shared server, you 'share' server space with other members. Though no other member has access to your files, you and the other members share all the resources of the server. This means that if one member is using a lot of CPU, RAM or storage, server performance may be degraded for other members.
 
Please adhere to the following rules:
    1. Be respectful of other users:
        - Do not attempt to access any other users' data
        - Keep your storage space usage to a minimum
        - Avoid running CPU/memory intensive programs
    2. Do not perform any illegal or malicious actions, including:
        - Attempting to exploit the server
        - Hosting inappropriate or offensive content
        - Running illegal programs, such as torrenting or DDoSing
        - Admins will be regularly monitoring the server, and offenders 
			will be removed and may be reported to UCD
	3. Maintain your own backups
		- We will do our best to keep the server up and running, however
			there is no guarantee that the server will always be up
		       	and free of faults
		- Permanent data loss could potentially occur at any time
		- Usage of the server next year will of course depend on whether
			next year's comitte maintains the server
 
If you are ever unsure of something, feel free to ask the admins!\n\n" | fold -s
